# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49aab31d1db594dad92ed194a670ae52e2e852a2f511a2c11d583ae413e4dacb574008f340e240b704bde3bceac2f015a62d53cc01a035f4302a675a18e96a7e

test:
  secret_key_base: 587a7850c96487462f85706d85458dceb6016daf40602d5280d50d3aa8b11ef6383c794b8ed90363893b717f0c9811c12270071a5acc4c4316aab5925258f8f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
